const allMenuItems = [
  {
    id: "multi-chat",
    label: "Мульти-чат AI",
    iconName: "MessageSquare",
    path: "/assistant/multi-chat",
    description: "Одновременное общение с несколькими AI-моделями",
    locations: ["sidebar"],
  },
  {
    id: "dashboard",
    label: "Ассистент",
    iconName: "Home",
    path: "/assistant",
    description: "Обзор ключевых метрик и быстрый доступ к функциям",
    locations: ["sidebar"],
  },
  {
    id: "tasks",
    label: "Задачи",
    iconName: "ListChecks",
    path: "/assistant/tasks",
    description: "Управление задачами и проектами",
    locations: ["sidebar"],
  },
  {
    id: "agents",
    label: "Агенты",
    iconName: "Users",
    path: "/agents",
    description: "Управление AI-агентами для автоматизации задач",
    locations: ["sidebar"],
    children: [
      {
        id: "content-factory",
        label: "Контент-завод",
        iconName: "FileText",
        path: "/agents/content-factory",
        description: "Автоматическая генерация и публикация контента",
        locations: ["sidebar"],
      },
      {
        id: "marketing",
        label: "Маркетинг",
        iconName: "TrendingUp",
        path: "/agents/marketing",
        description: "Маркетинговые агенты",
        locations: ["sidebar"],
      },
      {
        id: "smm",
        label: "SMM",
        iconName: "Share2",
        path: "/agents/smm",
        description: "SMM агенты",
        locations: ["sidebar"],
      },
      {
        id: "targetologist",
        label: "Таргетолог",
        iconName: "Target",
        path: "/agents/targetologist",
        description: "Таргетированная реклама",
        locations: ["sidebar"],
      },
      {
        id: "directologist",
        label: "Директолог",
        iconName: "Megaphone",
        path: "/agents/directologist",
        description: "Яндекс.Директ агенты",
        locations: ["sidebar"],
      },
      {
        id: "sales-agent",
        label: "Агент по продажам",
        iconName: "Phone",
        path: "/agents/sales",
        description:
          "Автоматизация процессов продаж и взаимодействия с клиентами",
        locations: ["sidebar"],
      },
      {
        id: "support",
        label: "Тех. поддержка",
        iconName: "Headphones",
        path: "/agents/support",
        description: "Техническая поддержка",
        locations: ["sidebar"],
      },
    ],
  },
  {
    id: "generations",
    label: "AI генерация",
    iconName: "Sparkles",
    path: "/generations",
    description: "Создание медиа-контента с помощью AI",
    locations: ["sidebar"],
    children: [
      {
        id: "text-generation",
        label: "Тексты",
        iconName: "Text",
        path: "/generations/text",
        description: "Создание текста по текстовому описанию",
        locations: ["sidebar"],
      },
      {
        id: "image-generation",
        label: "Изображения",
        iconName: "Image",
        path: "/generations/images",
        description: "Создание уникальных изображений с помощью AI",
        locations: ["sidebar"],
      },
      {
        id: "video-generation",
        label: "Видео",
        iconName: "Video",
        path: "/generations/video",
        description: "Создание видео-роликов по текстовому описанию",
        locations: ["sidebar"],
      },

      {
        id: "audio-generation",
        label: "Аудио",
        iconName: "Music",
        path: "/generations/audio",
        description: "Создание музыки и звуковых эффектов",
        locations: ["sidebar"],
      },
    ],
  },

  // {
  //   id: 'bot-management',
  //   label: 'Управление ботом',
  //   iconName: 'Bot',
  //   path: '/assistant/bot-management',
  //   description: 'Настройка и управление вашим Telegram ботом',
  //   locations: ['sidebar'],
  // },
  // {
  //   id: 'calendar-integration',
  //   label: 'Интеграция с календарем',
  //   iconName: 'Calendar',
  //   path: '/assistant/calendar-integration',
  //   description: 'Синхронизация с Google Calendar для управления событиями',
  //   locations: ['sidebar'],
  // },
  // {
  //   id: 'finances',
  //   label: 'Финансы',
  //   iconName: 'Landmark',
  //   path: '/finances',
  //   description: 'Управление балансом и тарифами',
  //   locations: ['sidebar'],
  //   children: [
  //     {
  //       id: 'token-history',
  //       label: 'История токенов',
  //       iconName: 'History',
  //       path: '/assistant/token-history',
  //       description: 'Просмотр истории пополнений и списаний токенов',
  //       locations: ['sidebar', 'profile'],
  //     },
  //   ],
  // },
  {
    id: "token-history",
    label: "История токенов",
    iconName: "Cpu",
    path: "/assistant/token-history",
    description: "История пополнений и списаний токенов",
    locations: ["profile"],
  },
  {
    id: "ai-settings",
    label: "Настройки AI",
    iconName: "Cpu",
    path: "/assistant/ai-settings",
    description: "Управление AI провайдерами и ключами",
    locations: ["profile"],
  },
  {
    id: "user-settings",
    label: "Настройки профиля",
    iconName: "Settings",
    path: "/assistant/user-settings",
    description: "Управление личными данными и настройками аккаунта",
    locations: ["profile"],
  },
];

module.exports = { allMenuItems };
